implement analysis memory reuse via output parameters
WorksApplications/sudachi.rs pull request #185
Opened 2021-11-30 09:19 UTC by eiennohito

Implement out parameters for `Tokenizer.tokenize()` and `Morpheme.split()` Python API.

For the memory sharing to be actually useful, I had to refactor internal MorphemeList to allow multiple references to input data, while having distinct list of morphemes. Let's welcome `Arc<RefCell<X>>` in our codebase.
Python `MorphemeListWrapper` has also changed. As a side effect there is no copy in custom pretokenizers (win). Need to document semantics of everything, but will do that as a documentation pass.

2021-12-01 06:13 UTC, mh-northlander requested changes
`Arc<RefCell>` is not thread safe: https://doc.rust-lang.org/std/sync/struct.Arc.html#thread-safety
we may use `Mutex` or `RwLock` instead of `RefCell`.

2021-12-01 06:13 UTC, mh-northlander commented on python/tests/test_morpheme.py
> +        ms = self.tokenizer_obj.tokenize("京都東京都京都", SplitMode.C)
I want to check the second split with different word from the above one.

2021-12-01 06:13 UTC, mh-northlander commented on sudachi/tests/stateful_tokenizer.rs
> +    assert_eq!(m.surface().deref().deref(), "東京都");
double deref?

2021-12-01 06:13 UTC, mh-northlander commented on sudachi/tests/stateless_tokenizer.rs
> +    let pos = ms[0].part_of_speech();
We can now access nodes by `ms.get(0)` instead of `ms[0]`. (same for other test functions)

2021-12-01 07:35 UTC, eiennohito commented on python/tests/test_morpheme.py
> +        ms = self.tokenizer_obj.tokenize("京都東京都京都", SplitMode.C)
Test binary dictionary has only 東京都 as a word with splits. I also wanted to check another word, but alas.
Moving all tests to using non-binary dictionary will fix this issue

2021-12-01 07:39 UTC, eiennohito commented
`Arc<RefCell<T>>` by itself is not thread-safe and that's OK. For the Python bindings, all accesses to MorphemeList happen under GIL and are OK, for Rust compiler will check invalid data sharing. 
After second thought, it is OK to make internals to be even `Rc<RefCell<T>>`.

2021-12-01 07:43 UTC, eiennohito commented on sudachi/tests/stateless_tokenizer.rs
> +    let pos = ms[0].part_of_speech();
Tests need more cleanup, I agree.

2021-12-01 09:07 UTC, eiennohito commented
@mh-northlander comments should be addressed

2021-12-02 02:24 UTC, mh-northlander approved these changes

2021-12-02 02:31 UTC, merged