add Dictionary.lookup method
WorksApplications/sudachi.rs pull request #221
Opened 2022-10-05 07:42 UTC by eiennohito

it fetches entries from the dictionary without doing analysis

2022-10-12 10:01 UTC, mh-northlander requested changes
Error occurs when I call `end` of resulting Morpheme:

```
> dict = sudachipy.Dictionary()
> mrps = dict.lookup("東京都")
> mrps[0].end()
thread '<unnamed>' panicked at 'index out of bounds: the len is 4 but the index is 9', sudachi-lib/src/input_text/buffer/mod.rs:332:24
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyo3_runtime.PanicException: index out of bounds: the len is 4 but the index is 9
```

Maybe the byte/char length conversion is the cause.

2022-10-12 10:01 UTC, mh-northlander commented on python/src/dictionary.rs
> +    #[pyo3(text_signature = "($self, surface, list = None) -> sudachipy.MorphemeList")]
3rd arg `list` seems not renamed (provably `out`).

2022-10-25 23:17 UTC, eiennohito commented
@mh-northlander thanks for the catch, fixed logic and added tests, both in Python and Rust for the logic

2022-11-01 06:46 UTC, mh-northlander approved these changes

2022-11-01 07:27 UTC, merged