Add option for embedded config and fallback resources
WorksApplications/sudachi.rs pull request #262
Opened 2024-06-13 16:32 UTC by Kuuuube

Partial fix for #218

Allows static binaries to function properly in rust by falling back on default config and resources. Missing support for user defined embedded files but I think sudachi.rs should have at least basic support for static binaries.

Basic example code creating a tokenizer using embedded defaults (dictionary must still be added separately):

```rust
let embedded_dictionary = include_bytes!("./system_full.dic");
let sudachi_dic_data = SudachiDicData::new(Storage::Borrowed(embedded_dictionary));
let config = Config::new_embedded().unwrap();
let japanese_dictionary = JapaneseDictionary::from_embedded_storage(&config, sudachi_dic_data).unwrap();

let tokenizer = StatelessTokenizer::new(&japanese_dictionary);
```

2024-06-26 01:26 UTC, mh-northlander requested changes
Ideally the embedded resource files should be used as a system default (replacing current default-resource-directory based configuration).
But as a first step we can have both.

I accept this PR with some miner changes.

2024-06-26 01:26 UTC, mh-northlander commented on sudachi/src/config.rs
> +        // prioritize arg (cli option) > default
this comment should be removed (this method does not take args from cli)

2024-06-26 01:26 UTC, mh-northlander commented on sudachi/src/dic/mod.rs
> +        let character_category = CharacterCategory::from_bytes(include_bytes!("../../../resources/char.def"))?;
Let's add const `DEFAULT_CHAR_DEF_BYTES` for this include bytes.

2024-06-26 01:26 UTC, mh-northlander commented on sudachi/src/dic/mod.rs
> +    pub fn from_system_dictionary_embedded(
This method shares main logic with `from_system_dictionary`.
Let's add following method to split shared part.

```
pub fn from_system_dictionary_and_chardef(
        dictionary_bytes: &'a [u8],
        character_category: CharacterCategory,
)
```

2024-06-26 01:26 UTC, mh-northlander commented on sudachi/src/dic/dictionary.rs
> +    pub fn from_embedded_storage(
I want to give more explicit name for this method like:
```
/// Creates a dictionary from the specified configuration and storage, with embedded character definition
pub fn from_cfg_storage_with_embedded_chardef(...
```

2024-06-26 04:26 UTC, Kuuuube commented
Thank you for the review! Everything should be resolved.

2024-06-27 02:54 UTC, mh-northlander approved these changes

2024-06-27 04:17 UTC, mh-northlander commented
@Kuuuube  please apply `cargo fmt`.

2024-06-27 05:08 UTC, Kuuuube commented
Done

2024-06-28 01:11 UTC, merged