fix dictionary.__repr__ for no user-dict case
WorksApplications/sudachi.rs pull request #282
Opened 2024-12-02 09:19 UTC by mh-northlander

current __repr__ misses close "]" with no user dict:

```python
dict = sp.Dictionary()
dict.__repr__()
# '<SudachiDictionary(system=/path/to/system.dic, user=[)>'
```

2024-12-03 07:06 UTC, kazuma-t requested changes

2024-12-03 07:06 UTC, kazuma-t commented on python/src/dictionary.rs
> +                if i + 1 != dicts.len() {
Wouldn't `i < dict.len()` be better?

2024-12-03 23:24 UTC, kazuma-t commented on python/src/dictionary.rs
> +                if i + 1 != dicts.len() {
Sorry, `i < dict.len() - 1`. Both are equally complicated, so you probably don't need to fix it.

2024-12-04 06:44 UTC, mh-northlander commented
`Vec<T>` does not have the display trait and we need to write.
https://doc.rust-jp.rs/rust-by-example-ja/hello/print/print_display.html

I chose to branch at index=0.

2024-12-04 07:19 UTC, kazuma-t approved these changes

2024-12-04 07:20 UTC, merged