Add morpheme_list
WorksApplications/sudachi.rs pull request #65
Opened 2021-10-05 02:36 UTC by mh-northlander

2021-10-05 02:40 UTC, mh-northlander commented
Maybe it's better to let `Morpheme` have `Deref<morpheme-list>` instead of the reference to concrete `MorphemeList` type

2021-10-05 04:47 UTC, eiennohito requested changes

2021-10-05 04:47 UTC, eiennohito commented on sudachi/src/analysis/morpheme_list.rs
> +    fn get_word_info(&self, index: usize) -> WordInfo {
this should be `&WordInfo`

2021-10-05 04:47 UTC, eiennohito commented on sudachi/src/analysis/morpheme_list.rs
> +    fn get_surface(&self, index: usize) -> &String {
this should be `&str`. Python wrapper should explicitly convert `&str` to PyString

2021-10-05 04:47 UTC, eiennohito commented on sudachi/src/analysis/morpheme_list.rs
> +    word_info: Option<crate::dic::lexicon::word_infos::WordInfo>,
this fully-qualified type should be in uses

2021-10-05 04:47 UTC, eiennohito commented on sudachi/src/analysis/morpheme_list.rs
> +    pub fn surface(&self) -> &String {
`&str` to all strings

2021-10-05 04:47 UTC, eiennohito commented on sudachi/src/analysis/morpheme_list.rs
> +    pub fn part_of_speech(&mut self) -> &Vec<String> {
`&Vec<T>` -> `&[T]` globally

2021-10-05 04:47 UTC, eiennohito commented on sudachi/src/analysis/morpheme_list.rs
> +    fn split(&self, mode: Mode, index: usize, word_info: WordInfo) -> usize {
impossible to implement in the current contract

2021-10-05 06:57 UTC, eiennohito commented
Also, I didn't understand the comment about `Deref`.

2021-10-05 08:02 UTC, mh-northlander commented
> Also, I didn't understand the comment about `Deref`.

I'm wondering if we can reuse code in python bind part like:
```rust
// rust side
struct Morpheme<T> {
    list: T,
    index: usize,
}
impl <T> Morpheme where T: Deref, <T as Deref>::Target: MorphemeListTrait {
    /// 
}

// python side
impl MorphemeListTrait for PyMorphemeList { /// }

struct PyMorpheme {
    inner: Morpheme<Arc<PyMorphemeList>>
}
```

2021-10-05 08:15 UTC, eiennohito commented
I believe that Pyo3 does not allow to expose methods from trait implementations to Python, so that part can't go away.

Also, lazy loading WordInfo will require having mutable references to everything, which is not a good thing.

2021-10-06 02:09 UTC, mh-northlander commented
> I believe that Pyo3 does not allow to expose methods from trait implementations to Python, so that part can't go away.

Yes, anyway we need to write code to expose functions.
I leave this idea for later.

> Also, lazy loading WordInfo will require having mutable references to everything, which is not a good thing.
I faced problems around this and remove WordInfo field.

2021-10-06 08:08 UTC, mh-northlander commented
I changed the type of `MorphemeList.input_text` from `&str` to `String`.
I guess it's better to have `&str` from the view point of allocation, but failed to pass the reference to the original input text through analysis.

2021-10-06 09:16 UTC, eiennohito commented
It's OK to have the String there internally. In the memory reuse case we will swap it with the Utf8InputText buffer.

2021-10-06 10:20 UTC, eiennohito commented on python/src/morpheme_list.rs
> +    fn synonym_group_ids(&self) -> Vec<u32> {
&[u32]

2021-10-06 10:20 UTC, eiennohito commented on sudachi/src/analysis/morpheme_list.rs
> +    pub fn split(&self, mode: Mode, index: usize) -> SudachiResult<MorphemeList<T>> {
As a general question, does it make sense to split only a single morpheme inside a path? (Except maybe tests)

Maybe the current Python API requires this, but we can provide better way to do things and deprecate bad ways later.
Usually we want to split the whole path at the same time, I believe.

2021-10-06 10:20 UTC, eiennohito commented on sudachi/src/lib.rs
> +        analysis::morpheme_list::MorphemeList,
I think there is no need to rename morpheme -> morpheme_list (because the morpheme is more domain-specific thing that the list of them).

2021-10-07 01:54 UTC, mh-northlander commented on sudachi/src/analysis/morpheme_list.rs
> +    pub fn split(&self, mode: Mode, index: usize) -> SudachiResult<MorphemeList<T>> {
I think it's possible that user want to change the split mode based on morpheme information (e.g. pos?).
I'll ask other people about this.

2021-10-07 02:34 UTC, mh-northlander commented on python/src/morpheme_list.rs
> +    fn synonym_group_ids(&self) -> Vec<u32> {
pyo3 cannot automatically convert &[T] into a python list and we need to return owned vec.

ref: [pymethod constraint](https://pyo3.rs/latest/conversions/tables.html#:~:text=IntoPy%3CPyObject%3E%20is%20required%20for%20function%20return%20values.), [pyo3::IntoPy](https://pyo3.rs/main/doc/pyo3/conversion/trait.IntoPy.html#)

2021-10-07 06:27 UTC, eiennohito commented on python/src/morpheme_list.rs
> +    fn synonym_group_ids(&self) -> Vec<u32> {
Then PyList directly at least (otherwise there are two conversions happening here).

2021-10-07 06:28 UTC, eiennohito commented on sudachi/src/analysis/morpheme_list.rs
> +    pub fn split(&self, mode: Mode, index: usize) -> SudachiResult<MorphemeList<T>> {
I think that that change is out of scope for this PR (because it is a change of API). Let's move it to another issue.

2021-10-07 08:15 UTC, eiennohito approved these changes

2021-10-07 08:15 UTC, eiennohito commented on python/src/dictionary.rs
> +    pub dictionary: Arc<JapaneseDictionary>,
you probably meant pub(super)

2021-10-07 09:20 UTC, merged