Split Node into smaller things
WorksApplications/sudachi.rs pull request #94
Opened 2021-10-13 08:38 UTC by eiennohito

Fixes #71, Fixes #81, Fixes #50

Split Node into:

* Node - produced by dictionary lookup (fast) and OOV
* V(iterbi)Node - used in analysis
* ResultNode - combination of first two plus WordInfo

Node always uses modified/rewritten indices
ResultNode uses modified indices during the path rewrite and original indices afterwards. It also holds both codepoint and byte indices to the data

WordId output changed to (dic_id, word_id).
dic_id is -1 for OOV only in output, internal value is 15=0xf.
This must be ported to Java.

2021-10-19 01:31 UTC, eiennohito commented
@mh-northlander I will add more documentation comments and check for unused InputBuffer methods, but this is almost ready.

2021-10-19 11:02 UTC, mh-northlander requested changes

2021-10-19 11:02 UTC, mh-northlander commented on python/src/morpheme.rs
> +#[pyclass(module = "sudachi.morpheme", name = "MorphemeList")]
this should be `sudachi.morphemelist` (for SudachiPy compatibility).

2021-10-19 11:02 UTC, mh-northlander commented on sudachi/src/input_text/buffer/mod.rs
> +    /// After building it is used as c2b for original data.
maybe this is `b2c`, based on l.200 `fn fill_orig_b2c`?

2021-10-19 11:07 UTC, eiennohito commented on python/src/morpheme.rs
> +#[pyclass(module = "sudachi.morpheme", name = "MorphemeList")]
Rebase fail.
But Tests didn't caught that.

2021-10-19 11:08 UTC, eiennohito commented on sudachi/src/input_text/buffer/mod.rs
> +    /// After building it is used as c2b for original data.
Thanks for the catch

2021-10-19 12:15 UTC, eiennohito commented on python/src/morpheme.rs
> +#[pyclass(module = "sudachi.morpheme", name = "MorphemeList")]
Also, it worked as is in test.
May be related to https://pyo3.rs/v0.14.5/module.html#python-submodules

2021-10-19 12:23 UTC, eiennohito commented
Ok, done, also added an import test for Python.

2021-10-20 01:36 UTC, mh-northlander approved these changes

2021-10-20 01:44 UTC, merged

2021-10-20 01:49 UTC, mh-northlander commented on python/src/morpheme.rs
> +#[pyclass(module = "sudachi.morpheme", name = "MorphemeList")]
This is actually kind of comment.
https://pyo3.rs/v0.14.5/class.html#customizing-the-class